<?php
session_start();
include 'db_connect.php';
require 'vendor/autoload.php'; // For Dompdf

use Dompdf\Dompdf;

if (!isset($_SESSION['admin_id'])) {
    header("Location: login.php");
    exit();
}

$admin_id = $_SESSION['admin_id'];
$report_id = uniqid("RPT_");
$report_type = "Admin Dashboard Report";
$file_format = "PDF";
$generated_on = date('Y-m-d H:i:s');
$status = "completed";
$remarks = "Report generated successfully";

// === Fetch summary statistics ===
$totalCustomersResult = mysqli_query($conn, "SELECT COUNT(*) AS total FROM users WHERE user_type='customer'");
$totalCustomers = mysqli_fetch_assoc($totalCustomersResult)['total'] ?? 0;

$today = date('Y-m-d');
$totalTransactionsResult = mysqli_query($conn, "SELECT COUNT(*) AS total FROM transactions WHERE DATE(date)='$today'");
$totalTransactions = mysqli_fetch_assoc($totalTransactionsResult)['total'] ?? 0;

$totalDepositsResult = mysqli_query($conn, "SELECT SUM(amount) AS total FROM transactions WHERE type='credit'");
$totalDeposits = mysqli_fetch_assoc($totalDepositsResult)['total'] ?? 0;

$totalTransfersResult = mysqli_query($conn, "SELECT SUM(amount) AS total FROM transactions WHERE type='debit' AND recipient_account IS NOT NULL");
$totalTransfers = mysqli_fetch_assoc($totalTransfersResult)['total'] ?? 0;

$totalRejectedUsersResult = mysqli_query($conn, "SELECT COUNT(*) AS total FROM users WHERE user_type='customer' AND account_status='Suspended'");
$totalRejectedUsers = mysqli_fetch_assoc($totalRejectedUsersResult)['total'] ?? 0;

// === Fetch all users ===
$allUsersResult = mysqli_query($conn, "SELECT id AS customer_id, first_name, last_name, email, phone_number, account_status AS status FROM users WHERE user_type='customer' ORDER BY date_created DESC");
$allUsers = mysqli_fetch_all($allUsersResult, MYSQLI_ASSOC);

// === Recent admin logins ===
$recentLoginsResult = mysqli_query($conn, "SELECT id AS admin_id, first_name, last_name, last_login AS login_time FROM users WHERE user_type='admin' ORDER BY last_login DESC LIMIT 5");
$recentLogins = mysqli_fetch_all($recentLoginsResult, MYSQLI_ASSOC);

// === Recent transactions ===
$recentTransactionsResult = mysqli_query($conn, "SELECT id AS trx_id, user_id AS admin_id, amount, type AS action, status, date AS created_at FROM transactions ORDER BY date DESC LIMIT 5");
$recentTransactions = mysqli_fetch_all($recentTransactionsResult, MYSQLI_ASSOC);

// === Build HTML content ===
$html = '
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Admin Report</title>
<style>
body { font-family: Arial, sans-serif; color: #222; background: #f7f7f7; }
.container { max-width: 900px; margin: auto; background: #fff; padding: 20px; border-radius: 8px; }
h1, h2 { color: #003366; }
table { width: 100%; border-collapse: collapse; margin-top: 10px; }
th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
th { background-color: #f0f4f8; }
tr:nth-child(even) { background-color: #eef6ff; }
.summary { margin-bottom: 20px; }
</style>
</head>
<body>
<div class="container">
<h1>Zuri Banking - Admin Report</h1>
<p><strong>Generated by Admin ID:</strong> '.$admin_id.' | <strong>On:</strong> '.$generated_on.'</p>

<div class="summary">
<h2>Summary</h2>
<p>Total Customers: '.$totalCustomers.'</p>
<p>Total Transactions Today: '.$totalTransactions.'</p>
<p>Total Deposits: Ksh '.number_format($totalDeposits,2).'</p>
<p>Total Transfers: Ksh '.number_format($totalTransfers,2).'</p>
<p>Total Rejected Users: '.$totalRejectedUsers.'</p>
</div>

<h2>All Registered Users</h2>
<table>
<tr><th>ID</th><th>First Name</th><th>Last Name</th><th>Email</th><th>Phone</th><th>Status</th></tr>';
foreach($allUsers as $user){
    $html .= "<tr>
    <td>{$user['customer_id']}</td>
    <td>{$user['first_name']}</td>
    <td>{$user['last_name']}</td>
    <td>{$user['email']}</td>
    <td>{$user['phone_number']}</td>
    <td>{$user['status']}</td>
    </tr>";
}
$html .= '</table>

<h2>Recent Admin Logins</h2>
<table>
<tr><th>Admin ID</th><th>Name</th><th>Login Time</th></tr>';
foreach($recentLogins as $login){
    $html .= "<tr>
    <td>{$login['admin_id']}</td>
    <td>{$login['first_name']} {$login['last_name']}</td>
    <td>{$login['login_time']}</td>
    </tr>";
}
$html .= '</table>';

$html .= '<h2>Recent Transactions</h2>
<table>
<tr><th>Transaction ID</th><th>User ID</th><th>Amount</th><th>Action</th><th>Status</th><th>Date</th></tr>';
foreach($recentTransactions as $trx){
    $html .= "<tr>
    <td>{$trx['trx_id']}</td>
    <td>{$trx['admin_id']}</td>
    <td>Ksh ".number_format($trx['amount'],2)."</td>
    <td>{$trx['action']}</td>
    <td>{$trx['status']}</td>
    <td>{$trx['created_at']}</td>
    </tr>";
}
$html .= '</table>
</div>
</body>
</html>';

// === Generate PDF ===
$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

// Save PDF to server
$folder = 'reports/';
if(!is_dir($folder)){ mkdir($folder,0777,true);}
$filename = $folder.'admin_report_'.time().'.pdf';
file_put_contents($filename, $dompdf->output());

// Insert record into reports table
$stmt = $conn->prepare("INSERT INTO reports (report_id, admin_id, report_type, file_format, file_path, generated_on, status, remarks) VALUES (?,?,?,?,?,?,?,?)");
$stmt->bind_param("sissssss", $report_id, $admin_id, $report_type, $file_format, $filename, $generated_on, $status, $remarks);
$stmt->execute();

echo "Report generated successfully! <a href='$filename' target='_blank'>View PDF</a>";
?>
