// report_generate.js

document.addEventListener("DOMContentLoaded", () => {
  const form = document.querySelector("form");
  const message = document.getElementById("report-message");
  const historyTable = document.querySelector(".report-table-container tbody");
  const generateBtn = document.getElementById("generate-report-btn");

  form.addEventListener("submit", (e) => {
    e.preventDefault(); // Prevent page reload for demo
    
    // Get form values
    const reportType = document.getElementById("report-type").value;
    const dateFrom = document.getElementById("date-from").value;
    const dateTo = document.getElementById("date-to").value;
    const format = document.getElementById("output-format").value;

    // Validate form fields
    if (!reportType || !dateFrom || !dateTo || !format) {
      message.textContent = "⚠️ Please fill in all required fields.";
      message.style.color = "red";
      return;
    }

    // Simulate generating a new report ID
    const reportId = "RPT-" + new Date().getFullYear() + getRandomNumber();
    const generatedOn = new Date().toLocaleString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit"
    });
    const adminId = "ADM-005"; // Can be dynamic in backend
    const filePath = `/Reports/${reportId}.pdf`;

    // Display success message
    message.textContent = `✅ Report "${reportType}" generated successfully (${format.toUpperCase()}).`;
    message.style.color = "green";

    // Add the new report to the table dynamically
    const newRow = document.createElement("tr");
    newRow.innerHTML = `
      <td data-label="Report ID">${reportId}</td>
      <td data-label="Generated On">${generatedOn}</td>
      <td data-label="Generated By">${adminId}</td>
      <td data-label="Report Type">${formatReportType(reportType)}</td>
      <td data-label="File Format">${format.toUpperCase()}</td>
      <td data-label="Action">
        <a href="${filePath}" download>Download</a> | 
        <a href="${filePath}" target="_blank">View</a>
      </td>
    `;
    historyTable.prepend(newRow); // Add new report at the top

    // Reset form fields
    form.reset();
  });

  // Helper function to generate random report numbers
  function getRandomNumber() {
    const random = Math.floor(1000 + Math.random() * 9000);
    return `-${random}`;
  }

  // Helper function to format report type names
  function formatReportType(type) {
    switch (type) {
      case "transaction_summary": return "Transaction Summary";
      case "daily_activity": return "Daily Activity";
      case "account_growth": return "Account Growth";
      case "failed_transactions": return "Failed Transactions";
      case "security_logs": return "Security Logs";
      default: return "Custom Report";
    }
  }
});
